apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      containers:
        - command:
            - /app/argocd-notifications-controller
          workingDir: /app
          image: argoprojlabs/argocd-notifications:latest
          imagePullPolicy: Always
          name: argocd-notifications-controller
      serviceAccountName: argocd-notifications-controller
