site_name: Argo CD Notifications
repo_url: https://github.com/argoproj-labs/argocd-notifications
strict: true
google_analytics:
- 'UA-105170809-5'
- 'auto'

theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
markdown_extensions:
- codehilite
- admonition
- markdown_include.include:
    base_path: docs
- toc:
    permalink: true
nav:
  - Overview: index.md
  - Triggers and Templates:
    - triggers_and_templates/index.md
    - triggers_and_templates/slack.md
  - Notification Services:
    - services/overview.md
    - services/slack.md
    - services/opsgenie.md
    - services/telegram.md
  - Recipients:
    - recipients/overview.md
    - recipients/bot.md
    - recipients/slack-bot.md
    - recipients/opsgenie-bot.md
    - recipients/telegram-bot.md
  - built-in.md
