apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-notifications-bot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-notifications-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-bot
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-bot
subjects:
- kind: ServiceAccount
  name: argocd-notifications-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-controller
subjects:
- kind: ServiceAccount
  name: argocd-notifications-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-bot
spec:
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-notifications-bot
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-bot
    spec:
      containers:
      - command:
        - /app/argocd-notifications
        - bot
        image: argoprojlabs/argocd-notifications:latest
        imagePullPolicy: Always
        name: argocd-notifications-bot
        workingDir: /app
      serviceAccountName: argocd-notifications-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      containers:
      - command:
        - /app/argocd-notifications
        - controller
        image: argoprojlabs/argocd-notifications:latest
        imagePullPolicy: Always
        name: argocd-notifications-controller
        workingDir: /app
      serviceAccountName: argocd-notifications-controller
