apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    email:
      host: smtp.gmail.com
      port: 587
      from: <myemail>@gmail.com
      username: <myemail>@gmail.com
      password: <mypassword>
    slack:
      token: <my-token>
      username: <override-username> # optional username
    opsgenie:
      apiUrl: api.opsgenie.com
      apiKeys:
        <team-id>: <my-api-key>
        ...
type: Opaque
