apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  # Notifier format key is: notifier.<type>.<optional-custom-name>

  # Slack
  notifier.slack: |
    token: <my-token>
    username: <override-username> # optional username
    icon: <override-icon> # optional icon for the message (supports both emoij and url notation)

  # Slack based notifier with name mattermost
  notifier.slack.mattermost: |
    apiURL: https://my-mattermost-url.com/api
    token: <my-token>
    username: <override-username> # optional username
    icon: <override-icon> # optional icon for the message (supports both emoij and url notation)

  # Email
  notifier.email: |
    host: smtp.gmail.com
    port: 587
    from: <myemail>@gmail.com
    username: <myemail>@gmail.com
    password: <mypassword>

  # Opsgenie
  notifier.opsgenie: |
    apiUrl: api.opsgenie.com
    apiKeys:
      <team-id>: <my-api-key>
      ...
type: Opaque
